server:
  port: 8080
  servlet:
    context-path: /jwt-authentification
eureka:
  client:
   register-with-eureka: false
   fetch-registry: false
   serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: jwt-authentification
    hostname: localhost

spring:
  application:
    name: jwt-authentification

logging:
  level:
    com.heyou: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

keys:
  public: public.pem
  private: private.key

crypto:
  algorithme: RSA

jwt:
  secret: 'The specified key byte array is 48 bits which is not secure enough for any JWT HMAC-SHA algorithm.'